### Coin Section
coin:
  display_name: Coin
  smelt_exp: 0
  smelt_time: 200
  use_head: false # If true, heads are used instead of standard items

  # Only needed if use_head is false
  item_material: POISONOUS_POTATO
  use_resource_pack: true
  resource_pack_url: https://raw.githubusercontent.com/Sowasvonbot/mc-coins/main/resource-packs/poisonous_potato_pack.zip

  # Links to https://minecraft-heads.com/custom-heads/head/63067-bag-of-coins
  # The Player UUID is called Minecraft URL on minecraft-heads
  # Only needed if use_head is true
  head_value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTVmZDY3ZDU2ZmZjNTNmYjM2MGExNzg3OWQ5YjUzMzhkNzMzMmQ4ZjEyOTQ5MWE1ZTE3ZThkNmU4YWVhNmMzYSJ9fX0=
  head_player_uuid: c7b55c30-93db-43b2-a108-47eae22a2a4a

coin_sign:
  prefix: "[coins]"

storage_chest:
  prefix: "[trading]"

coin_messages:
  fake_coin: This coin might be fake!
  real_coin: This is gold, believe it

command_message:
  # %d will be replaced with the coin amount.
  coins: You have %d coins buffered at the moment

error_messages:
  create_coin_chest: Error creating the coin chest
  create_trading_sign: |
    Error creating the trading sign.
    Maybe the first slot was not empty!
  invalid_trade_chest: Trade chest invalid, please replace the sign
  not_coin_during_pay: You have to use coins to pay and click an empty slot!
