name: ${artifactId}
version: ${version}
api-version: 1.19
author: Sowasvonbot
description: "Add real coins to the world of Minecraft"
website: "https://github.com/Sowasvonbot/mc-coins"
main: com.github.sowasvonbot.RealCoinsPlugin

commands:
  coins:
    description: shows your buffered coins
    usage: /<command>
